name: build-docker
description: Build docker image
inputs:
  context:
    required: false
    default: .
  dockerfile:
    required: false
    default: Dockerfile
  image:
    required: false
    default: local/test-image
runs:
  using: composite
  steps:
    - run: |
        docker build -f ${{ inputs.dockerfile }} ${{ inputs.context }} -t ${{ inputs.image }}
      shell: bash
