name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: |
          if (Test-Path *.sln) { dotnet restore (Get-ChildItem *.sln | Select-Object -First 1) } else { dotnet restore }
      - name: Build
        run: |
          if (Test-Path *.sln) { dotnet build (Get-ChildItem *.sln | Select-Object -First 1) -c Release --nologo } else { dotnet build -c Release --nologo }
      - name: Pack NT8 (optional)
        if: success()
        run: |
          if (Test-Path src\FKS.csproj) { dotnet build src\FKS.csproj -c Release --nologo }