name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Test
        run: cargo test --all --quiet
      - name: Schema Assert
        if: hashFiles('schema_assert.py') != ''
        run: |
          sudo apt-get update && sudo apt-get install -y python3 || true
          python3 schema_assert.py || (echo 'Schema mismatch' && exit 1)
