name: lint-rust
description: Run cargo fmt + clippy
runs:
  using: composite
  steps:
    - run: |
        rustup component add clippy rustfmt || true
        cargo fmt -- --check
        cargo clippy --all-targets -- -D warnings
      shell: bash
